language: python
sudo: false

python:
  - "3.5"

env:
  - TOXENV=py34-django18
  - TOXENV=py35-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=py35-flake8

install:
  - pip install tox

script:
  - tox -e $TOXENV
