# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 11:16
from __future__ import unicode_literals

import buckets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', buckets.fields.S3FileField()),
            ],
        ),
    ]
