# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 03:26
from __future__ import unicode_literals

import buckets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=buckets.fields.S3FileField(blank=True, null=True, upload_to='test'),
        ),
    ]
